### ISSUE TITLE
Did this ever reach functionality?

### ISSUE THREAD

**Issue by nevaldiv** [deanpcmad/gorails-downloader#1]
I was hoping to use this just now, and got error:
[Imgur screenshot](http://i.imgur.com/Kxr2woZ.png)

maybe there were changes to the site that make this tool no longer work?
Hope its an easy fix for a real rails dev like yourself, it would be a great resource to people like me who are still learning.

**Comment by idoan** [comment]
@nevaldiv It seems video urls have changed, let's try this.
 add `puts missing_videos_urls.to_s`  at line  30 and try again. It will give the same error but at least we will see a more meaningful output this time. and paste it here.

**Comment by deanpcmad** [comment]
Windows doesn't have curl built in so that would need to be installed. 
I've just tried the script on my Mac and it runs fine:
![](https://files.deanpcmad.com/2016/Screen-Shot-2016-06-07-17-26-24.png)

**Comment by nevaldiv** [comment]
yeah, right you are. 
sorry just dealing with transitioning from a mac to windows work enviroment and its rough, lol.

works now, for future notice windows users have to specify certain SSL enviroment variables and install curl, as well as edit some of the code like `-mv` to `move` for it to work in the windows command prompt.  but it does work.  thanks!

**Comment by deanpcmad** [comment]
You might be interested in this - http://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/
